// Auto-generated from Localizable.xcstrings — do not edit by hand.
import Foundation

enum GeneratedLocalizations {
    static let en: [String: String] = [
        "%@ %@": "%1$@ %2$@",
        "%@ dose": "%@ dose",
        "%@%@": "%1$@%2$@",
        "%lld day streak": "%lld day streak",
        "%lld days left": "%lld days left",
        "%lld days left in this month.": "%lld days left in this month.",
        "%lld days taken": "%lld days taken",
        "%lld medications": "%lld medications",
        "%lld medicines at this time": "%lld medicines at this time",
        "%lld of %lld days logged as taken this month.": "%lld of %lld days logged as taken this month.",
        "%lld of %lld doses done": "%lld of %lld doses done",
        "%lld readings": "%lld readings",
        "%lld readings today": "%lld readings today",
        "%lld taken · %lld skipped · %lld pending": "%lld taken · %lld skipped · %lld pending",
        "A day counts when today’s medication is marked Taken.": "A day counts when today’s medication is marked Taken.",
        "About_Us_Content": "PillPal is designed to help you easily track your daily medications and health data. It's a simple, intuitive, and privacy-respecting tool to make managing your health easier.\n\nThank you for using our app!",
        "Add Medication": "Add Medication",
        "Add Photo": "Add Photo",
        "Add Reading": "Add Reading",
        "Add Reminder": "Add Reminder",
        "Add reminder times in Reminder Times settings.": "Add reminder times in Reminder Times settings.",
        "Add your medications": "Add your medications",
        "Adherence: %lld%%": "Adherence: %lld%%",
        "Afternoon": "Afternoon",
        "All reminder times taken today": "All reminder times taken today",
        "All times": "All times",
        "App Settings": "App Settings",
        "Average": "Average",
        "Beats per minute": "Beats per minute",
        "Blood Pressure": "Blood Pressure",
        "Blood Pressure: %lld / %lld mmHg": "Blood Pressure: %lld / %lld mmHg",
        "BP History": "BP History",
        "BP Statistics": "BP Statistics",
        "BP Trends": "BP Trends",
        "Calendar day: %lld / %lld": "Calendar day: %lld / %lld",
        "Cancel": "Cancel",
        "CFBundleDisplayName": "PillPal",
        "Change Photo": "Change Photo",
        "Current Medications": "Current Medications",
        "Current streak: %lld days": "Current streak: %lld days",
        "Custom": "Custom",
        "Date": "Date",
        "Day Streak": "Day Streak",
        "day streak": "day streak",
        "Days": "Days",
        "Details": "Details",
        "Diastolic": "Diastolic",
        "Diastolic Range": "Diastolic Range",
        "Done": "Done",
        "Dose": "Dose",
        "Edit": "Edit",
        "Edit Blood Pressure": "Edit Blood Pressure",
        "Edit each reminder time for this day.": "Edit each reminder time for this day.",
        "Edit Heart Rate": "Edit Heart Rate",
        "Enable Daily Reminders": "Enable Daily Reminders",
        "Follow these steps to schedule multiple reminder times and assign medicines to each one.": "Follow these steps to schedule multiple reminder times and assign medicines to each one.",
        "Follow these steps to schedule reminder times and assign medicines to each one.": "Follow these steps to schedule reminder times and assign medicines to each one.",
        "Go to Profile to manage your medications, reminder times, and daily reminder notifications.": "Go to Profile to manage your medications, reminder times, and daily reminder notifications.",
        "Goal: %lld days": "Goal: %lld days",
        "Heart Rate": "Heart Rate",
        "Heart Rate (bpm)": "Heart Rate (bpm)",
        "Heart Rate (Optional)": "Heart Rate (Optional)",
        "Hello, %@!": "Hello, %@!",
        "Hello, Friend!": "Hello, Friend!",
        "High Blood Pressure": "High Blood Pressure",
        "High Heart Rate": "High Heart Rate",
        "High-Normal Blood Pressure": "High-Normal Blood Pressure",
        "History": "History",
        "How are you feeling today?": "How are you feeling today?",
        "How to set reminders & medications": "How to set reminders & medications",
        "How to Set Up": "How to Set Up",
        "HR History": "HR History",
        "HR Statistics": "HR Statistics",
        "HR Trends": "HR Trends",
        "Ideal Blood Pressure": "Ideal Blood Pressure",
        "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time with the medicines for that slot.": "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time.",
        "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time.": "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time.",
        "Keep taking your medicines to grow your streak.": "Keep taking your medicines to grow your streak.",
        "Label (e.g. Morning)": "Label (e.g. Morning)",
        "Language": "Language",
        "Let's stay on track today.": "Let's stay on track today.",
        "Log Blood Pressure": "Log Blood Pressure",
        "Log each reminder time": "Log each reminder time",
        "Log Heart Rate": "Log Heart Rate",
        "Low Blood Pressure": "Low Blood Pressure",
        "Low Heart Rate": "Low Heart Rate",
        "Manage Reminders": "Manage Reminders",
        "Medical Card": "Medical Card",
        "Medication Name": "Medication Name",
        "Medication Reminder": "Medication Reminder",
        "Medications": "Medications",
        "Missed": "Missed",
        "Missed at %@": "Missed at %@",
        "Mood (Optional)": "Mood (Optional)",
        "Mood Trends": "Mood Trends",
        "Mood: ": "Mood: ",
        "Morning": "Morning",
        "Most Common": "Most Common",
        "Name Not Set": "Name Not Set",
        "Night": "Night",
        "No blood pressure data yet.": "No blood pressure data yet.",
        "No BP recorded for this day.": "No BP recorded for this day.",
        "No BP recorded today.": "No BP recorded today.",
        "No data to display yet.": "No data to display yet.",
        "No details available.": "No details available.",
        "No heart rate recorded for this day.": "No heart rate recorded for this day.",
        "No heart rate recorded today.": "No heart rate recorded today.",
        "No medicines assigned yet.": "No medicines assigned yet.",
        "No mood data yet this month.": "No mood data yet this month.",
        "No reminders yet.": "No reminders yet.",
        "Normal": "Normal",
        "Normal Blood Pressure": "Normal Blood Pressure",
        "Normal Heart Rate": "Normal Heart Rate",
        "Not Recorded": "Not Recorded",
        "OK": "OK",
        "On Home, check your day streak and this month rings, then use Take Now or Missed when you finish or skip a dose. Tap a streak colour to see that reminder’s details.": "On Home, check your day streak and this month rings, then use Take Now or Missed when you finish or skip a dose. Tap a streak colour to see that reminder’s details.",
        "On Home, log each reminder with Take Now or Skip / Missed, and record how you feel.": "On Home, log each reminder with Take Now or Skip / Missed, and record how you feel.",
        "Open Profile": "Open Profile",
        "Open Profile → Manage Medications. Add each medicine and dose, then assign it to reminder times.": "Open Profile → Manage Medications. Add each medicine and dose, then assign it to reminder times.",
        "Open Profile → Manage Medications. Add each medicine and dose, then choose which reminder times it should use — or keep All times.": "Open Profile → Manage Medications. Add each medicine and dose, then choose which reminder times it should use — or keep All times.",
        "Open Profile → Reminder Times. Add one or more daily alarms (for example Morning, Afternoon, and Night), and pick a custom time for each.": "Open Profile → Reminder Times. Add one or more daily alarms (for example Morning, Afternoon, and Night), and pick a custom time for each.",
        "Open Profile → Reminder Times. Add one or more daily alarms (Morning, Afternoon, Night, or Custom).": "Open Profile → Reminder Times. Add one or more daily alarms (Morning, Afternoon, Night, or Custom).",
        "Patient": "Patient",
        "Pending": "Pending",
        "Personal Info": "Personal Info",
        "PillPal": "PillPal",
        "Profile": "Profile",
        "Range": "Range",
        "Reaction:": "Reaction:",
        "Readings": "Readings",
        "Recent Trends": "Recent Trends",
        "Recorded": "Recorded",
        "Remaining": "Remaining",
        "Remark (optional)": "Remark (optional)",
        "Remind at": "Remind at",
        "Reminder": "Reminder",
        "Reminder & Medication Guide": "Reminder & Medication Guide",
        "Reminder History": "Reminder History",
        "Reminder time: %@": "Reminder time: %@",
        "Reminder Times": "Reminder Times",
        "Reminders": "Reminders",
        "Remove": "Remove",
        "Save": "Save",
        "Save Record": "Save Record",
        "Save Settings": "Save Settings",
        "Scheduled · %@": "Scheduled · %@",
        "Set one or more daily reminder times. Assign medicines to each time on the Medications page.": "Set one or more daily reminder times. Assign medicines to each time on the Medications page.",
        "Set reminder times": "Set reminder times",
        "Shows your daily status without medicine names.": "Shows your daily status without medicine names.",
        "Skip / Missed": "Skip / Missed",
        "Skipped": "Skipped",
        "Slightly High Blood Pressure": "Slightly High Blood Pressure",
        "Stay on track with your health": "Stay on track with your health",
        "Streak": "Streak",
        "System": "System",
        "Systolic": "Systolic",
        "Systolic Range": "Systolic Range",
        "Take Now": "Take Now",
        "Taken": "Taken",
        "Taken this month: %lld": "Taken this month: %lld",
        "Tap a colour for month details": "Tap a colour for month details",
        "Tap a colour for reminder details": "Tap a colour for reminder details",
        "Tap a ring for details": "Tap a ring for details",
        "Terms_Body_1": "This app is strictly a personal health tracking tool. It does not provide professional medical diagnoses or advice. Always consult a healthcare professional for medical concerns.",
        "Terms_Body_2": "We value your privacy. All your health data is stored locally on this device. We do not collect, sell, or share your sensitive health data with third parties. Device backups follow your iPhone settings.",
        "Terms_Body_3": "The developers are not liable for any health issues or consequences arising from the use of this app.",
        "Terms_Body_4": "We reserve the right to modify these terms at any time. Updates will be reflected within the app.",
        "Terms_Body_5": "All information and medication records entered in this app are strictly for your own personal reference.",
        "Terms_Content": "Welcome to PillPal.\n\n1. Nature of Service\nThis app is strictly a personal health tracking tool. It does not provide professional medical diagnoses or advice. Always consult a healthcare professional for medical concerns.\n\n2. Privacy\nWe value your privacy. All your health data is stored locally on this device. We do not collect, sell, or share your sensitive health data with third parties. Device backups follow your iPhone settings.\n\n3. Disclaimer\nThe developers are not liable for any health issues or consequences arising from the use of this app.\n\n4. Changes to Terms\nWe reserve the right to modify these terms at any time. Updates will be reflected within the app.\n\n5. Information for Reference Only\nAll information and medication records entered in this app are strictly for your own personal reference.",
        "Terms_Title_1": "1. Nature of Service",
        "Terms_Title_2": "2. Privacy",
        "Terms_Title_3": "3. Disclaimer",
        "Terms_Title_4": "4. Changes to Terms",
        "Terms_Title_5": "5. Information for Reference Only",
        "This export includes your health records. Only share it with people you trust.": "This export includes your health records. Only share it with people you trust.",
        "This Month": "This Month",
        "Time for your medication.": "Time for your medication.",
        "BP recorded today.": "BP recorded today.",
        "this month": "this month",
        "This reading is high. If you can, please talk to your family doctor.": "This reading is high. If you can, please talk to your family doctor.",
        "Today": "Today",
        "Today · %@": "Today · %@",
        "Today's Medication": "Today's Medication",
        "Today: %@": "Today: %@",
        "Track on Home": "Track on Home",
        "Turn on notifications": "Turn on notifications",
        "Type": "Type",
        "Undo": "Undo",
        "Upper 120–129 or lower 80–84": "Upper 120–129 or lower 80–84",
        "Upper 130–139 or lower 85–89": "Upper 130–139 or lower 85–89",
        "Upper 140+ or lower 90+": "Upper 140+ or lower 90+",
        "Upper under 120 and lower under 80": "Upper under 120 and lower under 80",
        "Upper under 90 or lower under 60": "Upper under 90 or lower under 60",
        "Value": "Value",
        "Version 1.0": "Version 1.0",
        "View BP Trends": "View BP Trends",
        "View HR Trends": "View HR Trends",
        "Vitals": "Vitals",
        "Vitals (Optional)": "Vitals (Optional)",
        "Your blood pressure looks healthy. Plan another check within two years.": "Your blood pressure looks healthy. Plan another check within two years.",
        "Your current day streak is %lld.": "Your current day streak is %lld.",
        "Your heart rate is a little low. If you feel dizzy or unwell, please talk to your family doctor.": "Your heart rate is a little low. If you feel dizzy or unwell, please talk to your family doctor.",
        "Your heart rate is high. If you can, please talk to your family doctor.": "Your heart rate is high. If you can, please talk to your family doctor.",
        "Your heart rate looks healthy. Keep checking from time to time.": "Your heart rate looks healthy. Keep checking from time to time.",
        "Your reading is a little high. Checking again within a year will help you stay on top of it.": "Your reading is a little high. Checking again within a year will help you stay on top of it.",
        "Adherence": "Adherence",
        "Add a family member to keep medicines, reminders, and history separate — all on this device.": "Add a family member to keep medicines, reminders, and history separate — all on this device.",
        "Add Person": "Add Person",
        "All data for this person will be removed from this device.": "All data for this person will be removed from this device.",
        "Complete days this week: %lld": "Complete days this week: %lld",
        "Delete Profile": "Delete Profile",
        "Delete \"%@\"?": "Delete \"%@\"?",
        "Due": "Due",
        "Due now": "Due now",
        "Family member": "Family member",
        "Follow-up reminder": "Follow-up reminder",
        "Household": "Household",
        "Me": "Me",
        "Profiles stay on this iPhone. No account needed.": "Profiles stay on this iPhone. No account needed.",
        "Reminders include Taken and Snooze actions.": "Reminders include Taken and Snooze actions.",
        "Scheduled": "Scheduled",
        "Snooze": "Snooze",
        "Snooze 10 min": "Snooze 10 min",
        "Snooze 30 min": "Snooze 30 min",
        "Snooze 1 hour": "Snooze 1 hour",
        "Snoozed": "Snoozed",
        "Snoozed until %@": "Snoozed until %@",
        "Still time for your medication.": "Still time for your medication.",
        "Still time to take %@": "Still time to take %@",
        "Switch Profile": "Switch Profile",
        "Version 1.1": "Version 1.1",
        "This Week": "This Week",
        "Weekly Summary": "Weekly Summary",
        "Who is this for?": "Who is this for?",
        "Clinic Visit Pack": "Clinic Visit Pack",
        "Clinic-ready summary": "Clinic-ready summary",
        "Share a bilingual summary for your clinic visit.": "Share a bilingual summary for your clinic visit.",
        "Prepared for %@": "Prepared for %@",
        "Uses only records already on this iPhone. Nothing is uploaded.": "Uses only records already on this iPhone. Nothing is uploaded.",
        "Visit pack disclaimer": "This is a user-generated log from PillPal. It is not a medical report, diagnosis, or official clinic record.",
        "Period": "Period",
        "Last 7 days": "Last 7 days",
        "Last 14 days": "Last 14 days",
        "Last %lld days": "Last %lld days",
        "Preview language": "Preview language",
        "The shared PDF includes English and Traditional Chinese.": "The shared PDF includes English and Traditional Chinese.",
        "Schedule": "Schedule",
        "Share PDF": "Share PDF",
        "No adherence history in this period.": "No adherence history in this period.",
        "No blood pressure recorded in this period.": "No blood pressure recorded in this period.",
        "No heart rate recorded in this period.": "No heart rate recorded in this period.",
        "No mood recorded in this period.": "No mood recorded in this period.",
        "On this device only": "On this device only",
        "Mood": "Mood",
        "%lld complete days in a row": "%lld complete days in a row",
        "Allergies": "Allergies",
        "Allergies (e.g. penicillin)": "Allergies (e.g. penicillin)",
        "Emergency Contact": "Emergency Contact",
        "ICE Name": "ICE Name",
        "ICE Phone": "ICE Phone",
        "Relationship": "Relationship",
        "No allergies recorded. Add them so this card is ready in an emergency.": "No allergies recorded. Add them so this card is ready in an emergency.",
        "No emergency contact yet. Add a name and phone number.": "No emergency contact yet. Add a name and phone number.",
        "Add a name in Profile": "Add a name in Profile",
        "Not an official medical ID": "This is not an official medical ID. For personal reference only.",
        "Edit Medical Card": "Edit Medical Card",
        "Fill in details": "Fill in details",
        "Offline QR": "Offline QR",
        "Show QR on this card": "Show QR on this card",
        "Optional. Encodes only the fields you choose. Works offline.": "Optional. Encodes only the fields you choose. Works offline.",
        "Include in QR": "Include in QR",
        "Turn on at least one field to encode.": "Turn on at least one field to encode.",
        "Keep this QR private. It is generated on this iPhone.": "Keep this QR private. It is generated on this iPhone.",
        "View Medical Card": "View Medical Card",
        "Care": "Care",
        "Show today for": "Show today for",
        "樂齡 Mode": "樂齡 Mode",
        "Larger text and high-contrast buttons for easier tapping.": "Larger text and high-contrast buttons for easier tapping.",
        "No profiles yet": "No profiles yet",
        "Add a person in Profile to start household care.": "Add a person in Profile to start household care.",
        "No one selected": "No one selected",
        "Choose at least one person on this iPhone.": "Choose at least one person on this iPhone.",
        "No doses scheduled today.": "No doses scheduled today.",
        "All done for today": "All done for today",
        "Version 1.2": "Version 1.2",
        "Shows your medication status and recent days.": "Shows your medication status and recent days.",
        "%lld taken · %lld skipped · %lld missed": "%lld taken · %lld skipped · %lld missed",
    ]

    static let zhHant: [String: String] = [
        "%@ dose": "%@服藥",
        "%lld": "%lld",
        "%lld / %lld mmHg": "%lld / %lld mmHg",
        "%lld day streak": "連續 %lld 天",
        "%lld days left": "剩餘 %lld 天",
        "%lld days left in this month.": "本月尚餘 %lld 天。",
        "%lld days taken": "已服用 %lld 天",
        "%lld medications": "%lld 種藥物",
        "%lld medicines at this time": "此時間有 %lld 種藥物",
        "%lld of %lld days logged as taken this month.": "本月已記錄服用 %lld / %lld 天。",
        "%lld of %lld doses done": "已完成 %lld / %lld 次",
        "%lld readings": "%lld 筆紀錄",
        "%lld readings today": "今日 %lld 筆紀錄",
        "%lld taken · %lld skipped · %lld pending": "已服用 %lld · 已錯過 %lld · 待服用 %lld",
        "%lld/30": "%lld/30",
        "18–24": "18–24 歲",
        "25–34": "25–34 歲",
        "35–44": "35–44 歲",
        "45–54": "45–54 歲",
        "55–64": "55–64 歲",
        "65+": "65 歲或以上",
        "A day counts when today’s medication is marked Taken.": "當日標記為「已服用」才會計入連續天數。",
        "About": "關於",
        "About Us": "關於我們",
        "About_Us_Content": "藥伴伴旨在幫助您輕鬆記錄日常服藥情況與健康數據。這是一個簡單、直觀且尊重隱私的追蹤工具，讓您的健康管理更加輕鬆。\n\n感謝您的使用與支持！",
        "Add Medication": "新增藥物",
        "Add Photo": "新增照片",
        "Add Reading": "新增紀錄",
        "Add remark (optional)": "新增備註（選填）",
        "Add Reminder": "新增提醒",
        "Add reminder times in Reminder Times settings.": "請先在「提醒時間」設定中新增提醒。",
        "Add your medications": "新增藥物",
        "Additional Notes (Optional)": "備註（選填）",
        "Adherence: %lld%%": "遵從率：%lld%%",
        "Afternoon": "下午",
        "Age Range": "年齡範圍",
        "All reminder times taken today": "今日所有提醒時間皆已服用",
        "All times": "所有時間",
        "App Settings": "應用程式設定",
        "Average": "平均值",
        "Bad": "不好",
        "Beats per minute": "每分鐘心跳次數",
        "Blood Pressure": "血壓",
        "Blood Pressure (mmHg)": "血壓 (mmHg)",
        "Blood Pressure: %lld / %lld mmHg": "血壓：%lld / %lld mmHg",
        "BP History": "血壓紀錄",
        "BP Statistics": "血壓統計",
        "BP Trends": "血壓趨勢",
        "Calendar day: %lld / %lld": "日曆日期：%lld / %lld",
        "Cancel": "取消",
        "CFBundleDisplayName": "藥伴伴",
        "Change Photo": "更換照片",
        "Contact Us": "聯絡我們",
        "Current Medications": "目前藥物",
        "Current streak: %lld days": "目前連續：%lld 天",
        "Custom": "自訂",
        "Daily Status": "每日狀態",
        "Data Export Report": "資料匯出報告",
        "Date": "日期",
        "Day Streak": "連續天數",
        "day streak": "連續天數",
        "Days": "天",
        "Details": "詳情",
        "Diastolic": "舒張壓",
        "Diastolic (Low)": "舒張壓 (低壓)",
        "Diastolic (Low) BP": "舒張壓 (低壓)",
        "Diastolic Range": "舒張壓範圍",
        "Doctor's Card": "醫生看診卡",
        "Done": "完成",
        "Dose": "劑量",
        "Dose (e.g., 1 pill)": "劑量（例如：1粒）",
        "Dose: %@": "劑量：%@",
        "Edit": "編輯",
        "Edit Blood Pressure": "編輯血壓",
        "Edit each reminder time for this day.": "編輯此日每個提醒時間的狀態。",
        "Edit Heart Rate": "編輯心率",
        "Enable Daily Reminders": "啟用每日提醒",
        "English": "English",
        "Excellent": "極佳",
        "Export Data": "匯出資料",
        "Exported At": "匯出時間",
        "Follow these steps to schedule multiple reminder times and assign medicines to each one.": "依照以下步驟設定多個提醒時間，並將藥物指定到對應時段。",
        "Follow these steps to schedule reminder times and assign medicines to each one.": "依照以下步驟設定提醒時間，並為每個時段指定藥物。",
        "Fri": "五",
        "Go to Profile to manage your medications, reminder times, and daily reminder notifications.": "前往個人檔案管理藥物、提醒時間與每日提醒通知。",
        "Goal: %lld days": "目標：%lld 天",
        "Good": "不錯",
        "Heart Rate": "心率",
        "Heart Rate (bpm)": "心率（次／分）",
        "Heart Rate (Optional)": "心率（選填）",
        "Hello!": "你好！",
        "Hello, %@": "你好，%@",
        "Hello, %@!": "%@，你好！",
        "Hello, Friend!": "你好，朋友！",
        "High Blood Pressure": "高血壓",
        "High Heart Rate": "心率偏高",
        "High-Normal Blood Pressure": "正常高值血壓",
        "History": "歷史記錄",
        "How are you feeling today?": "今天感覺如何？",
        "How to set reminders & medications": "如何設定提醒與藥物",
        "How to Set Up": "設定教學",
        "HR History": "心率歷史",
        "HR Statistics": "心率統計",
        "HR Trends": "心率趨勢",
        "Ideal Blood Pressure": "理想血壓",
        "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time with the medicines for that slot.": "在個人資料中開啟每日提醒，藥伴伴就會在各預定時間通知你。",
        "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time.": "在個人檔案開啟每日提醒，藥伴伴便會在每個排程時間通知你。",
        "Information for Reference Only": "資訊僅供參考",
        "Is Taken": "已服用",
        "It's time to take %@": "現在是服用 %@ 的時間了",
        "Keep taking your medicines to grow your streak.": "持續按時服藥，延續你的連續紀錄。",
        "Label (e.g. Morning)": "標籤（例如：早上）",
        "Language": "語言",
        "Last 30 Days": "過去 30 天",
        "Let's stay on track today.": "今天也要按時服藥喔。",
        "Log Blood Pressure": "記錄血壓",
        "Log each reminder time": "分別記錄每個提醒時間",
        "Log Heart Rate": "記錄心率",
        "Log Medication": "記錄服藥",
        "Log your medication directly from the Home Screen.": "直接從主畫面記錄服藥情況。",
        "Low Blood Pressure": "低血壓",
        "Low Heart Rate": "心率偏低",
        "Manage Medications": "管理藥物",
        "Manage Reminders": "管理提醒",
        "Marks medication as taken or skipped for the next reminder time today.": "將下一筆提醒標記為已服用或已跳過。",
        "Medical Card": "醫療卡",
        "Medication Details": "藥物詳情",
        "Medication Name": "藥名",
        "Medication Reminder": "服藥提醒",
        "Medications": "藥物",
        "Medications:": "藥物：",
        "Medicine: %@": "藥物：%@",
        "Missed": "錯過",
        "Missed at %@": "忘記時間：%@",
        "Missed Details": "忘記/跳過詳情",
        "Missed Medication": "忘記服藥",
        "Mon": "一",
        "Mood (Optional)": "心情（選填）",
        "Mood Trends": "心情趨勢",
        "Mood: ": "心情：",
        "Morning": "早上",
        "Most Common": "最常見",
        "My Data": "我的資料",
        "Name": "姓名",
        "Name Not Set": "尚未設定姓名",
        "Neutral": "普通",
        "Night": "晚上",
        "No blood pressure data yet.": "尚未有血壓資料。",
        "No BP recorded for this day.": "此日尚未記錄血壓。",
        "No BP recorded today.": "今日未記錄血壓。",
        "No data to display yet.": "尚無資料可顯示。",
        "No details available.": "暫無詳情。",
        "No heart rate recorded for this day.": "此日尚未記錄心率。",
        "No heart rate recorded today.": "今日未記錄心率。",
        "No medications added.": "尚未新增藥物。",
        "No medicines assigned yet.": "尚未指定藥物。",
        "No mood data yet this month.": "本月尚無心情資料。",
        "No reminders yet.": "尚未設定提醒。",
        "Normal": "正常",
        "Normal Blood Pressure": "正常血壓",
        "Normal Heart Rate": "心率正常",
        "Not Recorded": "尚未記錄",
        "Not recorded yet": "尚未記錄",
        "Not selected": "尚未選擇",
        "Not Taken": "未服用",
        "Notes: %@": "備註：%@",
        "OK": "好",
        "On Home, check your day streak and this month rings, then use Take Now or Missed when you finish or skip a dose. Tap a streak colour to see that reminder’s details.": "在首頁查看連續天數與本月環形統計，服用或錯過時使用「現在服用」或「錯過」。點擊連續天數的顏色可查看該提醒詳情。",
        "On Home, log each reminder with Take Now or Skip / Missed, and record how you feel.": "在今日頁面使用「現在服用」或「略過／錯過」記錄每次提醒，並記下心情。",
        "Open Profile": "打開個人檔案",
        "Open Profile → Manage Medications. Add each medicine and dose, then assign it to reminder times.": "打開個人檔案 → 管理藥物。新增每種藥物與劑量，並指定對應的提醒時間。",
        "Open Profile → Manage Medications. Add each medicine and dose, then choose which reminder times it should use — or keep All times.": "前往個人資料 → 管理藥物。新增每種藥物與劑量，再選擇對應的提醒時間，或維持「所有時間」。",
        "Open Profile → Reminder Times. Add one or more daily alarms (for example Morning, Afternoon, and Night), and pick a custom time for each.": "前往個人資料 → 提醒時間。新增一或多個每日鬧鐘（例如早上、下午、晚上），並自訂每個時間。",
        "Open Profile → Reminder Times. Add one or more daily alarms (Morning, Afternoon, Night, or Custom).": "打開個人檔案 → 提醒時間。新增一個或多個每日鬧鐘（早上、下午、晚上或自訂）。",
        "Overview": "總覽",
        "Patient": "病患",
        "Pending": "待服用",
        "Personal Info": "基本資料",
        "Physical Reaction (Optional)": "身體反應（選填）",
        "PillPal": "藥伴伴",
        "Profile": "個人資料",
        "Quick Action": "快速操作",
        "Range": "範圍",
        "Reaction:": "反應：",
        "Reaction: %@": "反應：%@",
        "Readings": "筆數",
        "Recent Trends": "近期趨勢",
        "Recorded": "已記錄",
        "Remaining": "剩餘",
        "Remark (optional)": "備註（選填）",
        "Remark:": "備註：",
        "Remind at": "提醒於",
        "Reminder": "提醒",
        "Reminder & Medication Guide": "提醒與藥物設定指南",
        "Reminder History": "提醒紀錄",
        "Reminder Time": "提醒時間",
        "Reminder time: %@": "提醒時間：%@",
        "Reminder Times": "提醒時間",
        "Reminders": "提醒",
        "Remove": "移除",
        "Sat": "六",
        "Save": "儲存",
        "Save Record": "儲存記錄",
        "Save Settings": "儲存設定",
        "Saved!": "已儲存！",
        "Scheduled for %@": "預定時間：%@",
        "Scheduled · %@": "排程 · %@",
        "Select age range": "請選擇年齡範圍",
        "Set one or more daily reminder times. Assign medicines to each time on the Medications page.": "可設定一個或多個每日提醒時間。請在「藥物」頁面將藥品指定到對應時間。",
        "Set reminder times": "設定提醒時間",
        "Shows medications and recent health data.": "顯示藥物及近期健康數據。",
        "Shows your daily status without medicine names.": "顯示每日狀態，不含藥名。",
        "Shows your medication status and day streak.": "顯示您的服藥狀態與連續天數。",
        "Skip": "跳過",
        "Skip / Missed": "跳過 / 忘記",
        "Skipped": "已跳過",
        "Skipped Today": "今日已跳過",
        "Slightly High Blood Pressure": "前期高血壓",
        "Status": "狀態",
        "Stay on track with your health": "一起守護你的健康節奏",
        "Streak": "連續",
        "Sun": "日",
        "System": "系統預設",
        "Systolic": "收縮壓",
        "Systolic (High)": "收縮壓 (高壓)",
        "Systolic (High) BP": "收縮壓 (高壓)",
        "Systolic Range": "收縮壓範圍",
        "Take": "服用",
        "Take Medication": "服用藥物",
        "Take Now": "現在服用",
        "Taken": "已服用",
        "Taken this month: %lld": "本月已服用：%lld",
        "Taken Today": "今日已服",
        "Tap a colour for month details": "點擊顏色查看本月詳情",
        "Tap a colour for reminder details": "點擊顏色查看提醒詳情",
        "Tap a ring for details": "點擊環形圖查看詳情",
        "Target Hour": "固定時間（小時）",
        "Target Minute": "固定時間（分鐘）",
        "Terms & Conditions": "條款與細則",
        "Terms_Body_1": "本應用程式僅作為個人健康記錄與追蹤工具，不提供任何專業的醫療診斷或建議。若您有任何醫療疑問，請務必諮詢專業醫師。",
        "Terms_Body_2": "我們非常重視您的隱私。您輸入的所有健康數據與個人資料均僅儲存於本裝置。我們不會收集、出售或與第三方分享您的任何敏感健康資料。裝置備份依您的 iPhone 設定而定。",
        "Terms_Body_3": "本應用程式開發團隊不對因使用本程式所記錄之數據或產生的任何健康狀況負擔法律責任。",
        "Terms_Body_4": "我們保留隨時修改本條款與細則的權利，更新後將於應用程式內公告。",
        "Terms_Body_5": "本應用程式內記錄的所有資訊與藥物資料僅供您個人參考使用。",
        "Terms_Content": "歡迎使用藥伴伴。\n\n1. 服務性質\n本應用程式僅作為個人健康記錄與追蹤工具，不提供任何專業的醫療診斷或建議。若您有任何醫療疑問，請務必諮詢專業醫師。\n\n2. 隱私權保護\n我們非常重視您的隱私。您輸入的所有健康數據與個人資料均僅儲存於本裝置。我們不會收集、出售或與第三方分享您的任何敏感健康資料。裝置備份依您的 iPhone 設定而定。\n\n3. 免責聲明\n本應用程式開發團隊不對因使用本程式所記錄之數據或產生的任何健康狀況負擔法律責任。\n\n4. 條款修改\n我們保留隨時修改本條款與細則的權利，更新後將於應用程式內公告。\n\n5. 資訊僅供參考\n本應用程式內記錄的所有資訊與藥物資料僅供您個人參考使用。",
        "Terms_Title_1": "1. 服務性質",
        "Terms_Title_2": "2. 隱私權保護",
        "Terms_Title_3": "3. 免責聲明",
        "Terms_Title_4": "4. 條款修改",
        "Terms_Title_5": "5. 資訊僅供參考",
        "Terrible": "糟糕",
        "This export includes your health records. Only share it with people you trust.": "此匯出檔包含您的健康紀錄，請只與您信任的人分享。",
        "This Month": "本月",
        "Time for your medication.": "該服藥了。",
        "BP recorded today.": "今日已記錄血壓。",
        "this month": "本月",
        "This reading is high. If you can, please talk to your family doctor.": "這次血壓偏高，有空的話請徵詢家庭醫生的意見。",
        "Thu": "四",
        "Time": "時間",
        "Today": "今天",
        "Today · %@": "今天 · %@",
        "Today's Medication": "今日藥物",
        "Today: %@": "今天：%@",
        "Track on Home": "在今日頁面記錄",
        "Tue": "二",
        "Turn on notifications": "開啟通知",
        "Type": "類型",
        "Under 18": "18 歲以下",
        "Undo": "復原",
        "Upper 120–129 or lower 80–84": "收縮壓 120–129 或/和舒張壓 80–84 mmHg",
        "Upper 130–139 or lower 85–89": "收縮壓 130–139 或/和舒張壓 85–89 mmHg",
        "Upper 140+ or lower 90+": "收縮壓 ≥140 或/和舒張壓 ≥90 mmHg",
        "Upper under 120 and lower under 80": "收縮壓 <120 且舒張壓 <80 mmHg",
        "Upper under 90 or lower under 60": "收縮壓 <90 或/和舒張壓 <60 mmHg",
        "Value": "數值",
        "Version 1.0": "版本 1.0",
        "View BP Trends": "查看血壓趨勢",
        "View HR Trends": "查看心率趨勢",
        "Vitals": "生命體徵",
        "Vitals (Optional)": "生命體徵 (選填)",
        "Wed": "三",
        "Your blood pressure looks healthy. Plan another check within two years.": "血壓看起來不錯，建議兩年內再檢查一次，繼續保持。",
        "Your current day streak is %lld.": "你目前的連續天數是 %lld。",
        "Your heart rate is a little low. If you feel dizzy or unwell, please talk to your family doctor.": "你的心率略為偏低。如感到暈眩或不適，請向家庭醫生查詢。",
        "Your heart rate is high. If you can, please talk to your family doctor.": "你的心率偏高。如方便，請向家庭醫生查詢。",
        "Your heart rate looks healthy. Keep checking from time to time.": "你的心率看起來健康。請繼續不時檢查。",
        "Your Medication": "你的藥物",
        "your medication": "您的藥物",
        "Your reading is a little high. Checking again within a year will help you stay on top of it.": "血壓稍微偏高一點，建議一年內再檢查一次，多留意自己的身體。",
        "繁體中文": "繁體中文",
        "Adherence": "遵從率",
        "Add a family member to keep medicines, reminders, and history separate — all on this device.": "新增家人後，藥物、提醒與紀錄會分開存放，全部只在這部裝置上。",
        "Add Person": "新增成員",
        "All data for this person will be removed from this device.": "此對象的藥物、提醒與紀錄將從本機刪除。",
        "Complete days this week: %lld": "本週完成 %lld 天",
        "Delete Profile": "刪除對象",
        "Delete \"%@\"?": "刪除「%@」？",
        "Due": "該服用",
        "Due now": "現在該服用",
        "Family member": "家人",
        "Follow-up reminder": "補提醒",
        "Household": "家庭成員",
        "Me": "我",
        "Profiles stay on this iPhone. No account needed.": "所有資料只存在這部 iPhone，無需登入。",
        "Reminders include Taken and Snooze actions.": "通知可直接標記已服用，或延後 10／30／60 分鐘。",
        "Scheduled": "已排程",
        "Snooze": "稍後提醒",
        "Snooze 10 min": "延後 10 分鐘",
        "Snooze 30 min": "延後 30 分鐘",
        "Snooze 1 hour": "延後 1 小時",
        "Snoozed": "已延後",
        "Snoozed until %@": "延後至 %@",
        "Still time for your medication.": "還有時間服藥。",
        "Still time to take %@": "別忘了服用 %@",
        "Switch Profile": "切換對象",
        "Version 1.1": "版本 1.1",
        "This Week": "本週",
        "Weekly Summary": "本週摘要",
        "Who is this for?": "這是誰的藥盒？",
        "Clinic Visit Pack": "覆診單",
        "Clinic-ready summary": "覆診用摘要",
        "Share a bilingual summary for your clinic visit.": "分享雙語摘要，方便覆診時給醫生參考。",
        "Prepared for %@": "對象：%@",
        "Uses only records already on this iPhone. Nothing is uploaded.": "只使用本機已有的紀錄，不會上傳。",
        "Visit pack disclaimer": "此為藥伴伴使用者自行產生的紀錄，並非醫療報告、診斷或正式診所文件。",
        "Period": "期間",
        "Last 7 days": "過去 7 天",
        "Last 14 days": "過去 14 天",
        "Last %lld days": "過去 %lld 天",
        "Preview language": "預覽語言",
        "The shared PDF includes English and Traditional Chinese.": "分享的 PDF 同時包含英文與繁體中文。",
        "Schedule": "服用時間",
        "Share PDF": "分享 PDF",
        "No adherence history in this period.": "這段期間尚未有服藥紀錄。",
        "No blood pressure recorded in this period.": "這段期間尚未記錄血壓。",
        "No heart rate recorded in this period.": "這段期間尚未記錄心率。",
        "No mood recorded in this period.": "這段期間尚未記錄心情。",
        "On this device only": "僅存於本機",
        "Mood": "心情",
        "%lld complete days in a row": "連續完成 %lld 天",
        "Allergies": "過敏",
        "Allergies (e.g. penicillin)": "過敏（例如：盤尼西林）",
        "Emergency Contact": "緊急聯絡人",
        "ICE Name": "緊急聯絡人姓名",
        "ICE Phone": "緊急聯絡電話",
        "Relationship": "關係",
        "No allergies recorded. Add them so this card is ready in an emergency.": "尚未記錄過敏。請填寫，以便緊急時使用。",
        "No emergency contact yet. Add a name and phone number.": "尚未設定緊急聯絡人。請填寫姓名與電話。",
        "Add a name in Profile": "請在個人資料填寫姓名",
        "Not an official medical ID": "這不是正式醫療證件，僅供個人參考。",
        "Edit Medical Card": "編輯醫療卡",
        "Fill in details": "填寫資料",
        "Offline QR": "離線 QR",
        "Show QR on this card": "在卡片上顯示 QR",
        "Optional. Encodes only the fields you choose. Works offline.": "選用功能。只會編碼你選擇的欄位，可離線使用。",
        "Include in QR": "編碼到 QR",
        "Turn on at least one field to encode.": "請至少選擇一個要編碼的欄位。",
        "Keep this QR private. It is generated on this iPhone.": "請妥善保管此 QR，它只在這部 iPhone 上產生。",
        "View Medical Card": "查看醫療卡",
        "Care": "照護",
        "Show today for": "顯示對象",
        "樂齡 Mode": "樂齡模式",
        "Larger text and high-contrast buttons for easier tapping.": "放大文字與高對比按鈕，方便點按。",
        "No profiles yet": "尚未有家庭成員",
        "Add a person in Profile to start household care.": "請在個人資料新增成員，即可開始家庭照護。",
        "No one selected": "尚未選擇對象",
        "Choose at least one person on this iPhone.": "請至少選擇一位本機成員。",
        "No doses scheduled today.": "今天沒有排程劑量。",
        "All done for today": "今天已全部完成",
        "Version 1.2": "版本 1.2",
        "Shows your medication status and recent days.": "顯示服藥狀態與近日紀錄。",
        "%lld taken · %lld skipped · %lld missed": "已服用 %lld · 已跳過 %lld · 錯過 %lld",
    ]
    
    /// English catalog `one` variants. 繁中 keeps a single form.
    private static let enOne: [String: String] = [
        "%lld readings": "%lld reading",
        "%lld readings today": "%lld reading today",
        "%lld complete days in a row": "%lld complete day in a row",
    ]
    
    static func pluralTemplate(_ key: String, count: Int, chinese: Bool) -> String? {
        guard enOne[key] != nil else { return nil }
        if chinese {
            return zhHant[key] ?? en[key]
        }
        if count == 1 {
            return enOne[key]
        }
        return en[key]
    }
}
