// Auto-generated from Localizable.xcstrings — do not edit by hand.
import Foundation

enum GeneratedLocalizations {
    static let en: [String: String] = [
        "%@ %@": "%1$@ %2$@",
        "%@ dose": "%@ dose",
        "%@%@": "%1$@%2$@",
        "%lld day streak": "%lld day streak",
        "%lld days left": "%lld days left",
        "%lld days left in this month.": "%lld days left in this month.",
        "%lld days taken": "%lld days taken",
        "%lld medications": "%lld medications",
        "%lld medicines at this time": "%lld medicines at this time",
        "%lld of %lld days logged as taken this month.": "%lld of %lld days logged as taken this month.",
        "%lld of %lld doses done": "%lld of %lld doses done",
        "%lld readings": "%lld readings",
        "%lld readings today": "%lld readings today",
        "%lld taken · %lld skipped · %lld pending": "%lld taken · %lld skipped · %lld pending",
        "A day counts when today’s medication is marked Taken.": "A day counts when today’s medication is marked Taken.",
        "About_Us_Content": "PillPal is designed to help you easily track your daily medications and health data. It's a simple, intuitive, and privacy-respecting tool to make managing your health easier.\n\nThank you for using our app!",
        "Add Medication": "Add Medication",
        "Add Photo": "Add Photo",
        "Add Reading": "Add Reading",
        "Add Reminder": "Add Reminder",
        "Add reminder times in Reminder Times settings.": "Add reminder times in Reminder Times settings.",
        "Add your medications": "Add your medications",
        "Adherence: %lld%%": "Adherence: %lld%%",
        "Afternoon": "Afternoon",
        "All reminder times taken today": "All reminder times taken today",
        "All times": "All times",
        "App Settings": "App Settings",
        "Average": "Average",
        "BP History": "BP History",
        "BP Statistics": "BP Statistics",
        "BP Trends": "BP Trends",
        "Blood Pressure": "Blood Pressure",
        "Blood Pressure: %lld / %lld mmHg": "Blood Pressure: %lld / %lld mmHg",
        "CFBundleDisplayName": "PillPal",
        "Calendar day: %lld / %lld": "Calendar day: %lld / %lld",
        "Cancel": "Cancel",
        "Change Photo": "Change Photo",
        "Current Medications": "Current Medications",
        "Current streak: %lld days": "Current streak: %lld days",
        "Custom": "Custom",
        "Date": "Date",
        "Day Streak": "Day Streak",
        "Days": "Days",
        "Details": "Details",
        "Diastolic": "Diastolic",
        "Diastolic Range": "Diastolic Range",
        "Done": "Done",
        "Dose": "Dose",
        "Edit": "Edit",
        "Edit Blood Pressure": "Edit Blood Pressure",
        "Edit each reminder time for this day.": "Edit each reminder time for this day.",
        "Enable Daily Reminders": "Enable Daily Reminders",
        "Follow these steps to schedule multiple reminder times and assign medicines to each one.": "Follow these steps to schedule multiple reminder times and assign medicines to each one.",
        "Follow these steps to schedule reminder times and assign medicines to each one.": "Follow these steps to schedule reminder times and assign medicines to each one.",
        "Go to Profile to manage your medications, reminder times, and daily reminder notifications.": "Go to Profile to manage your medications, reminder times, and daily reminder notifications.",
        "Goal: %lld days": "Goal: %lld days",
        "Hello, %@!": "Hello, %@!",
        "Hello, Friend!": "Hello, Friend!",
        "High Blood Pressure": "High Blood Pressure",
        "History": "History",
        "How are you feeling today?": "How are you feeling today?",
        "How to Set Up": "How to Set Up",
        "How to set reminders & medications": "How to set reminders & medications",
        "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time with the medicines for that slot.": "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time with the medicines for that slot.",
        "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time.": "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time.",
        "Keep taking your medicines to grow your streak.": "Keep taking your medicines to grow your streak.",
        "Label (e.g. Morning)": "Label (e.g. Morning)",
        "Language": "Language",
        "Let's stay on track today.": "Let's stay on track today.",
        "Log Blood Pressure": "Log Blood Pressure",
        "Log each reminder time": "Log each reminder time",
        "Manage Reminders": "Manage Reminders",
        "Medical Card": "Medical Card",
        "Medication Name": "Medication Name",
        "Medications": "Medications",
        "Missed": "Missed",
        "Missed at %@": "Missed at %@",
        "Mood (Optional)": "Mood (Optional)",
        "Mood Trends": "Mood Trends",
        "Mood: ": "Mood: ",
        "Morning": "Morning",
        "Most Common": "Most Common",
        "Name Not Set": "Name Not Set",
        "Night": "Night",
        "No BP recorded for this day.": "No BP recorded for this day.",
        "No blood pressure data yet.": "No blood pressure data yet.",
        "No data to display yet.": "No data to display yet.",
        "No details available.": "No details available.",
        "No medicines assigned yet.": "No medicines assigned yet.",
        "No mood data yet this month.": "No mood data yet this month.",
        "No reminders yet.": "No reminders yet.",
        "Normal": "Normal",
        "Not Recorded": "Not Recorded",
        "OK": "OK",
        "On Home, check your day streak and this month rings, then use Take Now or Missed when you finish or skip a dose. Tap a streak colour to see that reminder’s details.": "On Home, check your day streak and this month rings, then use Take Now or Missed when you finish or skip a dose. Tap a streak colour to see that reminder’s details.",
        "On Home, log each reminder with Take Now or Skip / Missed, and record how you feel.": "On Home, log each reminder with Take Now or Skip / Missed, and record how you feel.",
        "Open Profile": "Open Profile",
        "Open Profile → Manage Medications. Add each medicine and dose, then assign it to reminder times.": "Open Profile → Manage Medications. Add each medicine and dose, then assign it to reminder times.",
        "Open Profile → Manage Medications. Add each medicine and dose, then choose which reminder times it should use — or keep All times.": "Open Profile → Manage Medications. Add each medicine and dose, then choose which reminder times it should use — or keep All times.",
        "Open Profile → Reminder Times. Add one or more daily alarms (Morning, Afternoon, Night, or Custom).": "Open Profile → Reminder Times. Add one or more daily alarms (Morning, Afternoon, Night, or Custom).",
        "Open Profile → Reminder Times. Add one or more daily alarms (for example Morning, Afternoon, and Night), and pick a custom time for each.": "Open Profile → Reminder Times. Add one or more daily alarms (for example Morning, Afternoon, and Night), and pick a custom time for each.",
        "Patient": "Patient",
        "Pending": "Pending",
        "Personal Info": "Personal Info",
        "PillPal": "PillPal",
        "Profile": "Profile",
        "Reaction:": "Reaction:",
        "Readings": "Readings",
        "Recent Trends": "Recent Trends",
        "Recorded": "Recorded",
        "Remaining": "Remaining",
        "Remind at": "Remind at",
        "Reminder": "Reminder",
        "Reminder & Medication Guide": "Reminder & Medication Guide",
        "Reminder History": "Reminder History",
        "Reminder Times": "Reminder Times",
        "Reminder time: %@": "Reminder time: %@",
        "Reminders": "Reminders",
        "Remove": "Remove",
        "Save": "Save",
        "Save Record": "Save Record",
        "Save Settings": "Save Settings",
        "Scheduled · %@": "Scheduled · %@",
        "Set one or more daily reminder times. Assign medicines to each time on the Medications page.": "Set one or more daily reminder times. Assign medicines to each time on the Medications page.",
        "Set reminder times": "Set reminder times",
        "Skip / Missed": "Skip / Missed",
        "Skipped": "Skipped",
        "Slightly High Blood Pressure": "Slightly High Blood Pressure",
        "Stay on track with your health": "Stay on track with your health",
        "Streak": "Streak",
        "System": "System",
        "Systolic": "Systolic",
        "Systolic Range": "Systolic Range",
        "Take Now": "Take Now",
        "Taken": "Taken",
        "Taken this month: %lld": "Taken this month: %lld",
        "Tap a colour for month details": "Tap a colour for month details",
        "Tap a colour for reminder details": "Tap a colour for reminder details",
        "Tap a ring for details": "Tap a ring for details",
        "Terms_Body_1": "This app is strictly a personal health tracking tool. It does not provide professional medical diagnoses or advice. Always consult a healthcare professional for medical concerns.",
        "Terms_Body_2": "We value your privacy. All your health data is stored locally on your device and your personal iCloud account. We do not collect, sell, or share your sensitive health data with third parties.",
        "Terms_Body_3": "The developers are not liable for any health issues or consequences arising from the use of this app.",
        "Terms_Body_4": "We reserve the right to modify these terms at any time. Updates will be reflected within the app.",
        "Terms_Body_5": "All information and medication records entered in this app are strictly for your own personal reference.",
        "Terms_Content": "Welcome to PillPal.\n\n1. Nature of Service\nThis app is strictly a personal health tracking tool. It does not provide professional medical diagnoses or advice. Always consult a healthcare professional for medical concerns.\n\n2. Privacy\nWe value your privacy. All your health data is stored locally on your device and your personal iCloud account. We do not collect, sell, or share your sensitive health data with third parties.\n\n3. Disclaimer\nThe developers are not liable for any health issues or consequences arising from the use of this app.\n\n4. Changes to Terms\nWe reserve the right to modify these terms at any time. Updates will be reflected within the app.\n\n5. Information for Reference Only\nAll information and medication records entered in this app are strictly for your own personal reference.",
        "Terms_Title_1": "1. Nature of Service",
        "Terms_Title_2": "2. Privacy",
        "Terms_Title_3": "3. Disclaimer",
        "Terms_Title_4": "4. Changes to Terms",
        "Terms_Title_5": "5. Information for Reference Only",
        "This Month": "This Month",
        "This reading is high. If you can, please talk to your family doctor.": "This reading is high. If you can, please talk to your family doctor.",
        "Today": "Today",
        "Today · %@": "Today · %@",
        "Today's Medication": "Today's Medication",
        "Today: %@": "Today: %@",
        "Track on Home": "Track on Home",
        "Turn on notifications": "Turn on notifications",
        "Type": "Type",
        "Undo": "Undo",
        "Value": "Value",
        "Version 1.0": "Version 1.0",
        "View BP Trends": "View BP Trends",
        "Vitals": "Vitals",
        "Vitals (Optional)": "Vitals (Optional)",
        "Your blood pressure looks healthy. Plan another check within two years.": "Your blood pressure looks healthy. Plan another check within two years.",
        "Your current day streak is %lld.": "Your current day streak is %lld.",
        "Your reading is a little high. Checking again within a year will help you stay on top of it.": "Your reading is a little high. Checking again within a year will help you stay on top of it.",
        "day streak": "day streak",
        "this month": "this month",
    ]

    static let zhHant: [String: String] = [
        "%@ dose": "%@服藥",
        "%lld": "%lld",
        "%lld / %lld mmHg": "%lld / %lld mmHg",
        "%lld day streak": "連續 %lld 天",
        "%lld days left": "剩餘 %lld 天",
        "%lld days left in this month.": "本月尚餘 %lld 天。",
        "%lld days taken": "已服用 %lld 天",
        "%lld medications": "%lld 種藥物",
        "%lld medicines at this time": "此時間有 %lld 種藥物",
        "%lld of %lld days logged as taken this month.": "本月已記錄服用 %lld / %lld 天。",
        "%lld of %lld doses done": "已完成 %lld / %lld 次",
        "%lld readings": "%lld 筆紀錄",
        "%lld readings today": "今日 %lld 筆紀錄",
        "%lld taken · %lld skipped · %lld pending": "已服用 %lld · 已錯過 %lld · 待服用 %lld",
        "%lld/30": "%lld/30",
        "18–24": "18–24 歲",
        "25–34": "25–34 歲",
        "35–44": "35–44 歲",
        "45–54": "45–54 歲",
        "55–64": "55–64 歲",
        "65+": "65 歲或以上",
        "A day counts when today’s medication is marked Taken.": "當日標記為「已服用」才會計入連續天數。",
        "About": "關於",
        "About Us": "關於我們",
        "About_Us_Content": "藥伴伴旨在幫助您輕鬆記錄日常服藥情況與健康數據。這是一個簡單、直觀且尊重隱私的追蹤工具，讓您的健康管理更加輕鬆。\n\n感謝您的使用與支持！",
        "Add Medication": "新增藥物",
        "Add Photo": "新增照片",
        "Add Reading": "新增紀錄",
        "Add Reminder": "新增提醒",
        "Add remark (optional)": "新增備註（選填）",
        "Add reminder times in Reminder Times settings.": "請先在「提醒時間」設定中新增提醒。",
        "Add your medications": "新增藥物",
        "Additional Notes (Optional)": "備註（選填）",
        "Adherence: %lld%%": "遵從率：%lld%%",
        "Afternoon": "下午",
        "Age Range": "年齡範圍",
        "All reminder times taken today": "今日所有提醒時間皆已服用",
        "All times": "所有時間",
        "App Settings": "應用程式設定",
        "Average": "平均值",
        "BP History": "血壓紀錄",
        "BP Statistics": "血壓統計",
        "BP Trends": "血壓趨勢",
        "Bad": "不好",
        "Blood Pressure": "血壓",
        "Blood Pressure (mmHg)": "血壓 (mmHg)",
        "Blood Pressure: %lld / %lld mmHg": "血壓：%lld / %lld mmHg",
        "CFBundleDisplayName": "藥伴伴",
        "Calendar day: %lld / %lld": "日曆日期：%lld / %lld",
        "Cancel": "取消",
        "Change Photo": "更換照片",
        "Contact Us": "聯絡我們",
        "Current Medications": "目前藥物",
        "Current streak: %lld days": "目前連續：%lld 天",
        "Custom": "自訂",
        "Daily Status": "每日狀態",
        "Data Export Report": "資料匯出報告",
        "Date": "日期",
        "Day Streak": "連續天數",
        "Days": "天",
        "Details": "詳情",
        "Diastolic": "舒張壓",
        "Diastolic (Low)": "舒張壓 (低壓)",
        "Diastolic (Low) BP": "舒張壓 (低壓)",
        "Diastolic Range": "舒張壓範圍",
        "Doctor's Card": "醫生看診卡",
        "Done": "完成",
        "Dose": "劑量",
        "Dose (e.g., 1 pill)": "劑量（例如：1粒）",
        "Dose: %@": "劑量：%@",
        "Edit": "編輯",
        "Edit Blood Pressure": "編輯血壓",
        "Edit each reminder time for this day.": "編輯此日每個提醒時間的狀態。",
        "Enable Daily Reminders": "啟用每日提醒",
        "English": "English",
        "Excellent": "極佳",
        "Export Data": "匯出資料",
        "Exported At": "匯出時間",
        "Follow these steps to schedule multiple reminder times and assign medicines to each one.": "依照以下步驟設定多個提醒時間，並將藥物指定到對應時段。",
        "Follow these steps to schedule reminder times and assign medicines to each one.": "依照以下步驟設定提醒時間，並為每個時段指定藥物。",
        "Fri": "五",
        "Go to Profile to manage your medications, reminder times, and daily reminder notifications.": "前往個人檔案管理藥物、提醒時間與每日提醒通知。",
        "Goal: %lld days": "目標：%lld 天",
        "Good": "不錯",
        "Hello!": "你好！",
        "Hello, %@": "你好，%@",
        "Hello, %@!": "%@，你好！",
        "Hello, Friend!": "你好，朋友！",
        "High Blood Pressure": "高血壓",
        "History": "歷史記錄",
        "How are you feeling today?": "今天感覺如何？",
        "How to Set Up": "設定教學",
        "How to set reminders & medications": "如何設定提醒與藥物",
        "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time with the medicines for that slot.": "在個人資料中開啟每日提醒，藥伴伴就會在各時段通知你該吃的藥物。",
        "In Profile, enable Daily Reminders so PillPal can notify you at each scheduled time.": "在個人檔案開啟每日提醒，藥伴伴便會在每個排程時間通知你。",
        "Information for Reference Only": "資訊僅供參考",
        "Is Taken": "已服用",
        "It's time to take %@": "現在是服用 %@ 的時間了",
        "Keep taking your medicines to grow your streak.": "持續按時服藥，延續你的連續紀錄。",
        "Label (e.g. Morning)": "標籤（例如：早上）",
        "Language": "語言",
        "Last 30 Days": "過去 30 天",
        "Let's stay on track today.": "今天也要按時服藥喔。",
        "Log Blood Pressure": "記錄血壓",
        "Log Medication": "記錄服藥",
        "Log each reminder time": "分別記錄每個提醒時間",
        "Log your medication directly from the Home Screen.": "直接從主畫面記錄服藥情況。",
        "Manage Medications": "管理藥物",
        "Manage Reminders": "管理提醒",
        "Marks medication as taken or skipped for the next reminder time today.": "將下一筆提醒標記為已服用或已跳過。",
        "Medical Card": "醫療卡",
        "Medication Details": "藥物詳情",
        "Medication Name": "藥名",
        "Medication Reminder": "服藥提醒",
        "Medications": "藥物",
        "Medications:": "藥物：",
        "Medicine: %@": "藥物：%@",
        "Missed": "錯過",
        "Missed Details": "忘記/跳過詳情",
        "Missed Medication": "忘記服藥",
        "Missed at %@": "忘記時間：%@",
        "Mon": "一",
        "Mood (Optional)": "心情（選填）",
        "Mood Trends": "心情趨勢",
        "Mood: ": "心情：",
        "Morning": "早上",
        "Most Common": "最常見",
        "My Data": "我的資料",
        "Name": "姓名",
        "Name Not Set": "尚未設定姓名",
        "Neutral": "普通",
        "Night": "晚上",
        "No BP recorded for this day.": "此日尚未記錄血壓。",
        "No BP recorded today.": "今日未記錄血壓。",
        "No blood pressure data yet.": "尚未有血壓資料。",
        "No data to display yet.": "尚無資料可顯示。",
        "No details available.": "暫無詳情。",
        "No medications added.": "尚未新增藥物。",
        "No medicines assigned yet.": "尚未指定藥物。",
        "No mood data yet this month.": "本月尚無心情資料。",
        "No reminders yet.": "尚未設定提醒。",
        "Normal": "正常",
        "Not Recorded": "尚未記錄",
        "Not Taken": "未服用",
        "Not recorded yet": "尚未記錄",
        "Not selected": "尚未選擇",
        "Notes: %@": "備註：%@",
        "OK": "好",
        "On Home, check your day streak and this month rings, then use Take Now or Missed when you finish or skip a dose. Tap a streak colour to see that reminder’s details.": "在首頁查看連續天數與本月環形統計，服用或錯過時使用「現在服用」或「錯過」。點擊連續天數的顏色可查看該提醒詳情。",
        "On Home, log each reminder with Take Now or Skip / Missed, and record how you feel.": "在今日頁面使用「現在服用」或「略過／錯過」記錄每次提醒，並記下心情。",
        "Open Profile": "打開個人檔案",
        "Open Profile → Manage Medications. Add each medicine and dose, then assign it to reminder times.": "打開個人檔案 → 管理藥物。新增每種藥物與劑量，並指定對應的提醒時間。",
        "Open Profile → Manage Medications. Add each medicine and dose, then choose which reminder times it should use — or keep All times.": "前往個人資料 → 管理藥物。新增每種藥物與劑量，再選擇對應的提醒時間，或維持「所有時間」。",
        "Open Profile → Reminder Times. Add one or more daily alarms (Morning, Afternoon, Night, or Custom).": "打開個人檔案 → 提醒時間。新增一個或多個每日鬧鐘（早上、下午、晚上或自訂）。",
        "Open Profile → Reminder Times. Add one or more daily alarms (for example Morning, Afternoon, and Night), and pick a custom time for each.": "前往個人資料 → 提醒時間。新增一或多個每日鬧鐘（例如早上、下午、晚上），並自訂每個時間。",
        "Overview": "總覽",
        "Patient": "病患",
        "Pending": "待服用",
        "Personal Info": "基本資料",
        "Physical Reaction (Optional)": "身體反應（選填）",
        "PillPal": "藥伴伴",
        "Profile": "個人資料",
        "Quick Action": "快速操作",
        "Reaction:": "反應：",
        "Reaction: %@": "反應：%@",
        "Readings": "筆數",
        "Recent Trends": "近期趨勢",
        "Recorded": "已記錄",
        "Remaining": "剩餘",
        "Remark:": "備註：",
        "Remind at": "提醒於",
        "Reminder": "提醒",
        "Reminder & Medication Guide": "提醒與藥物設定指南",
        "Reminder History": "提醒紀錄",
        "Reminder Time": "提醒時間",
        "Reminder Times": "提醒時間",
        "Reminder time: %@": "提醒時間：%@",
        "Reminders": "提醒",
        "Remove": "移除",
        "Sat": "六",
        "Save": "儲存",
        "Save Record": "儲存記錄",
        "Save Settings": "儲存設定",
        "Saved!": "已儲存！",
        "Scheduled for %@": "預定時間：%@",
        "Scheduled · %@": "排程 · %@",
        "Select age range": "請選擇年齡範圍",
        "Set one or more daily reminder times. Assign medicines to each time on the Medications page.": "可設定一個或多個每日提醒時間。請在「藥物」頁面將藥品指定到對應時間。",
        "Set reminder times": "設定提醒時間",
        "Shows medications and recent health data.": "顯示藥物及近期健康數據。",
        "Shows your medication status and day streak.": "顯示您的服藥狀態與連續天數。",
        "Skip": "跳過",
        "Skip / Missed": "跳過 / 忘記",
        "Skipped": "已跳過",
        "Skipped Today": "今日已跳過",
        "Slightly High Blood Pressure": "前期高血壓",
        "Status": "狀態",
        "Stay on track with your health": "一起守護你的健康節奏",
        "Streak": "連續",
        "Sun": "日",
        "System": "系統預設",
        "Systolic": "收縮壓",
        "Systolic (High)": "收縮壓 (高壓)",
        "Systolic (High) BP": "收縮壓 (高壓)",
        "Systolic Range": "收縮壓範圍",
        "Take": "服用",
        "Take Medication": "服用藥物",
        "Take Now": "現在服用",
        "Taken": "已服用",
        "Taken Today": "今日已服",
        "Taken this month: %lld": "本月已服用：%lld",
        "Tap a colour for month details": "點擊顏色查看本月詳情",
        "Tap a colour for reminder details": "點擊顏色查看提醒詳情",
        "Tap a ring for details": "點擊環形圖查看詳情",
        "Target Hour": "固定時間（小時）",
        "Target Minute": "固定時間（分鐘）",
        "Terms & Conditions": "條款與細則",
        "Terms_Body_1": "本應用程式僅作為個人健康記錄與追蹤工具，不提供任何專業的醫療診斷或建議。若您有任何醫療疑問，請務必諮詢專業醫師。",
        "Terms_Body_2": "我們非常重視您的隱私。您輸入的所有健康數據與個人資料均僅儲存於您的設備及個人的 iCloud 帳號中。我們不會收集、出售或與第三方分享您的任何敏感健康資料。",
        "Terms_Body_3": "本應用程式開發團隊不對因使用本程式所記錄之數據或產生的任何健康狀況負擔法律責任。",
        "Terms_Body_4": "我們保留隨時修改本條款與細則的權利，更新後將於應用程式內公告。",
        "Terms_Body_5": "本應用程式內記錄的所有資訊與藥物資料僅供您個人參考使用。",
        "Terms_Content": "歡迎使用藥伴伴。\n\n1. 服務性質\n本應用程式僅作為個人健康記錄與追蹤工具，不提供任何專業的醫療診斷或建議。若您有任何醫療疑問，請務必諮詢專業醫師。\n\n2. 隱私權保護\n我們非常重視您的隱私。您輸入的所有健康數據與個人資料均僅儲存於您的設備及個人的 iCloud 帳號中。我們不會收集、出售或與第三方分享您的任何敏感健康資料。\n\n3. 免責聲明\n本應用程式開發團隊不對因使用本程式所記錄之數據或產生的任何健康狀況負擔法律責任。\n\n4. 條款修改\n我們保留隨時修改本條款與細則的權利，更新後將於應用程式內公告。\n\n5. 資訊僅供參考\n本應用程式內記錄的所有資訊與藥物資料僅供您個人參考使用。",
        "Terms_Title_1": "1. 服務性質",
        "Terms_Title_2": "2. 隱私權保護",
        "Terms_Title_3": "3. 免責聲明",
        "Terms_Title_4": "4. 條款修改",
        "Terms_Title_5": "5. 資訊僅供參考",
        "Terrible": "糟糕",
        "This Month": "本月",
        "This reading is high. If you can, please talk to your family doctor.": "這次血壓偏高，有空的話請徵詢家庭醫生的意見。",
        "Thu": "四",
        "Time": "時間",
        "Today": "今天",
        "Today · %@": "今天 · %@",
        "Today's Medication": "今日藥物",
        "Today: %@": "今天：%@",
        "Track on Home": "在今日頁面記錄",
        "Tue": "二",
        "Turn on notifications": "開啟通知",
        "Type": "類型",
        "Under 18": "18 歲以下",
        "Undo": "復原",
        "Value": "數值",
        "Version 1.0": "版本 1.0",
        "View BP Trends": "查看血壓趨勢",
        "Vitals": "生命體徵",
        "Vitals (Optional)": "生命體徵 (選填)",
        "Wed": "三",
        "Your Medication": "你的藥物",
        "Your blood pressure looks healthy. Plan another check within two years.": "血壓看起來不錯，建議兩年內再檢查一次，繼續保持。",
        "Your current day streak is %lld.": "你目前的連續天數是 %lld。",
        "Your reading is a little high. Checking again within a year will help you stay on top of it.": "血壓稍微偏高一點，建議一年內再檢查一次，多留意自己的身體。",
        "day streak": "連續天數",
        "this month": "本月",
        "your medication": "您的藥物",
        "繁體中文": "繁體中文",
    ]
}
